---
title: "Sokassági arány becslése"
author: "Granát Marcell"
output: github_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F, comment = "", fig.align = "center", fig.width = 9, fig.height = 6, dev = "svg")
library(tidyverse)
theme_set(ggdark::dark_theme_gray() + theme(
  legend.title = element_blank()
))
```

```{r}
p <- 50
n <- 100
alpha <- 5
```

```{r}
p <- p/100
  varp <- (p*(1-p))/(n-1)
  sdp <- varp^0.5
  zstat <- qnorm(1-alpha/200)
  conf_min <- p-sdp*zstat
  conf_max <- p+sdp*zstat
  needed_n <- ifelse(n*p < 10 | n*(1-p) < 10, "Szükséges mintaelemszám feltétele sérül!", "Mintaelemszám elégséges.")

    paste(
    "Mintabeli arány = ", scales::percent(p, accuracy = .01), "\n",
    needed_n, "\n",
    "Standard hiba = ", round(sdp, digits = 4), "\n",
    "Z = ", round(zstat, digits = 4), "\n",
    "Konfidencia intervallum alsó határa = ", scales::percent(conf_min, accuracy = .01), "\n",
    "Konfidencia intervallum felső határa = ", scales::percent(conf_max, accuracy = .01),
    sep = ""
  )
```