---
title: "Variancia becslése"
author: "Granát Marcell"
output: github_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F, comment = "", fig.align = "center", fig.width = 9, fig.height = 6, dev = "svg")
library(tidyverse)
theme_set(ggdark::dark_theme_gray() + theme(
  legend.title = element_blank()
))
```

```{r input}
ssd <- 1 #Mintabeli szórás
n <- 100 #Mintanagyság
alpha <- 5 #Szignifikanciaszint (%)
```

```{r answer}
 conf_var_min <- (n-1)*ssd^2/qchisq(1-alpha/200, df = n-1)
  conf_var_max <- (n-1)*ssd^2/qchisq(alpha/200, df = n-1)

  str_c(
    "Mintabeli szórás = ", round(ssd, digits = 4), "\n",
    "Variancia konfidencia-intervallumának alsó határa = ", round(conf_var_min, digits = 4), "\n",
    "Variancia konfidencia-intervallumának felső határa = ", round(conf_var_max, digits = 4), "\n",
    "Szórás konfidencia-intervallumának alsó határa = ",  round(conf_var_min^0.5, digits = 4), "\n",
    "Szórás konfidencia-intervallumának felső határa = ",round(conf_var_max^0.5, digits = 4)
  )
```


